config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'static#home'


  resources :recipients, only: [:index, :new]
  post "recipients/add_recipient" => 'recipients#add_recipient'
  get "recipients/add_payment" => 'recipients#add_payment'
  post "recipients/make_payment" => 'recipients#make_payment'
  get "recipients/get_payments" => 'recipients#get_payments'
  post "recipients/verify_payment" => 'recipients#verify_payment'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipients_controller.rb
class CoolpayController < ApplicationController
    require 'rest-client'
    USERNAME = 'Naz1'
    API_KEY = '6C5BC43B47397578'
    BASE_URI = 'https://coolpay.herokuapp.com/api'
    before_action :authenticate_coolpay
    #before_action :authenticate_coolpay, :index; :only => [:add_payment]

#authentication
    def authenticate_coolpay
  	uri = BASE_URI + '/login'
	header = {"content-type" => "application/json"}
  	body = {"username": USERNAME,"apikey": API_KEY}.to_json
  	response = RestClient.post(uri, body, header)
	@token = JSON.parse(response)['token']	
    end
    
#Listing recipients   
    def index
	uri = BASE_URI + '/recipients'
  	body = {"username": USERNAME,"apikey": API_KEY}.to_json
  	header = {"content-type" => "application/json","authorization" => "Bearer #{@token}"}
  	response = RestClient.get(uri, header)
  	@recipients = JSON.parse(response)["recipients"]
    end

#Add a new recipient
    def new
    end
    def add_recipient
	uri = BASE_URI + '/recipients'
  	header = {"content-type" => "application/json","authorization" => "Bearer #{@token}"}
  	body = {"recipient": {"name": params[:recipient],}}.to_json
  	RestClient.post(uri, body, header)
	redirect_to recipients_path
    end

#create a payment
    def add_payment
	index
    end
    def make_payment
	uri = BASE_URI + '/payments'
	body = {"payment": {"amount": params[:amount],"currency": params[:currency],"recipient_id": params[:recipient]}}.to_json
	header = {"content-type" => "application/json","authorization" => "Bearer #{@token}"
  	}
	response = RestClient.post(uri, body, header)
	redirect_to recipients_path
	
    end

# Verify a payment
    def get_payments
	uri = BASE_URI + '/payments'
	header = {"content-type" => "application/json","authorization" => "Bearer #{@token}"}
	response = RestClient.get(uri, header)
	@payments = JSON.parse(response)["payments"]
    end

    def verify_payment
	get_payments
	check_payment = @payments.select {|payment| payment["id"] == params[:payment_id]}.first["status"]
	#check_payment["status"]
	respond_to do |format|
	    if (check_payment == "paid")
		format.html{redirect_to({action: 'index'}, notice: 'Payment Successful')}
	    else
		format.html{redirect_to({action: 'index'}, notice: 'Payment Failed')}
	    end
	end
		
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoolpayApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipients/add_payment.html.erb
<p> Add a payment </p>

<form action='/recipients/make_payment' method='post'>
    <label for="recipient">Recipient Name</label>
    <select id="recipient" name="recipient" required>
	<option value=""> Select a recipient </option>
	<% @recipients.each do |r| %>
	    <option value="<%=  r["id"] %>" > <%= r["name"] %> </option>
        <% end %> 
    </select>

    <label for='amount'>Amount
        <input type='text' name='amount' id='amount' required: true/>
    </label>
    <label for='currency'>Currency </label>
<% if false %>
	<input type='text' name='currency' id='currency'/>
<% end %>
    <select id="currency" name="currency" required>
	<option value=""> Select Currency </option>
	<option value="USD"> USD </option>
	<option value="EUR"> EUR </option>
	<option value="INR"> INR </option>
	<option value="INR"> CAD </option>

    </select>
    

      <input type='submit' value='Make Payment'  />
    </form>
<%= link_to 'List of recipients', recipients_path %>

app/views/recipients/get_payments.html.erb
<h2> Select Payment ID </h2>

<form action='/recipients/verify_payment' method='post'>
      <label for="payment_id">Payment ID </label>
      <select id="payment_id" name="payment_id" required>
	<option value=""> Select a payment </option>
	<% @payments.each do |p| %>
	    <option value="<%=  p["id"] %>" > <%= p["id"] %> </option>
        <% end %> 
    </select>

      <input type='submit' value='Select Payment ID'  />
    </form>

<%= link_to 'List of recipients', recipients_path %>
<%= link_to 'Home', 'static/home' %>

app/views/recipients/index.html.erb
<h1>Listing Recipients</h1>

<table>
  <tr>
    <th>Recipient Name</th>
    <th>Recipient ID</th>
  </tr>

<% @recipients.each do |recipient| %>
  <tr>
    <td><%= recipient["name"] %></td>
    <td><%= recipient["id"] %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to('Add a Recipient', new_recipient_path) %>
<%= link_to('Make a Payment', '/recipients/add_payment') %>
<%= link_to('Verify a Payment', '/recipients/get_payments') %>

app/views/recipients/new.html.erb
<p> Add a new Recipient </p>

<form action='/recipients/add_recipient' method='post'>
      <label for='recipient'>Recipient Name
        <input type='text' name='recipient' id='recipient' required='true'/>
      </label>
      <input type='submit' value='Add Recipient'  />
</form>
<%= link_to 'List of recipients', recipients_path %>